name: MARKDOWN-LINT

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  markdown-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v4.0.1
      with:
        node-version: ${{ vars.CURRENT_NODE_VERSION }}
    - run: cd website && npm ci
    - run: cd website && npm run-script lint-styles
